spring.datasource.url=jdbc:postgresql://dpg-d58dofu3jp1c73bevge0-a
spring.datasource.username=postgres
spring.datasource.password=mat_khau_cua_em
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect