spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Cấu hình JWT Secret
jwt.secret=RkdRUTNFSFBQdUpHVTJWNFRFU1RLRVlmb3IyNTZiaXRzSg==
# 24 giờ (miliseconds)
jwt.expiration=86400000 
# 7 ngày
jwt.refresh.expiration=604800000
# Cấu hình CORS (Cho phép React frontend gọi API)
cors.allowed.origins=http://localhost:5173,http://127.0.0.1:5173

spring.servlet.multipart.max-request-size=100MB
