spring.application.name=backend
spring.datasource.url=jdbc:postgresql://dpg-d58dofu3jp1c73bevge0-a.singapore-postgres.render.com:5432/mini_social_networl_db?currentSchema=public&timezone=Asia/Ho_Chi_Minh
spring.datasource.username=mini_social_networl_db_user
spring.datasource.password=wVh5v1Ml8fVBbGhDM57YhNn68SsewSaq
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Cấu hình JWT Secret
jwt.secret=RkdRUTNFSFBQdUpHVTJWNFRFU1RLRVlmb3IyNTZiaXRzSg==
# 24 giờ (miliseconds)
jwt.expiration=86400000 
# 7 ngày
jwt.refresh.expiration=604800000
# Cấu hình CORS (Cho phép React frontend gọi API)
cors.allowed.origins=http://localhost:5173,http://127.0.0.1:5173

app.upload.dir=uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Ép Jackson format ngày tháng theo múi giờ VN
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# Format date cho đẹp (tùy chọn)
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss